server:
  port: 8090
spring:
  application:
    name: busia
  #数据库连接相关配置
  datasource:
    url: jdbc:mysql://192.168.1.208:3307/test?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    #阿里巴巴的druid的mysql连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  #rabbitmq的配置
  rabbitmq:
    host: 192.168.1.208
    port: 5672
